name: Update Twitch clips

on:
  workflow_dispatch:
  schedule:
    - cron: "17 6 * * *"  # quotidien ~06:17 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i node-fetch@3

      - name: Fetch latest clips -> clips.json
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_USER_LOGIN: ${{ secrets.TWITCH_USER_LOGIN }}
        run: node .github/workflows/scripts/fetch_clips.mjs

      - name: Commit changes if any
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add clips.json
            git commit -m "Update clips.json (latest 5 by date)"
            git push
          fi

