name: Update YouTube videos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # toutes les 6h (à ta guise)

jobs:
  update-youtube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (node-fetch)
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i node-fetch@3

      - name: Fetch latest YouTube videos
        env:
          YOUTUBE_HANDLE: ${{ secrets.YOUTUBE_HANDLE }}
        run: node .github/workflows/scripts/fetch_youtube_rss.mjs

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add youtube.json
          git diff --cached --quiet || git commit -m "chore: update youtube.json"
          git push

