name: Update TikTok videos

on:
  workflow_dispatch:
  schedule:
    - cron: "23 6 * * *" # tous les jours ~06:23 UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i node-fetch@3

      - name: Fetch latest TikTok videos -> tiktok.json
        env:
          TIKTOK_API_KEY: ${{ secrets.TIKTOK_API_KEY }}
          TIKTOK_USER: ${{ secrets.TIKTOK_USER }}
        run: node .github/workflows/scripts/fetch_tiktok.mjs

      - name: Commit changes if any
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add tiktok.json
            git commit -m "Update tiktok.json (latest 6 by date)"
            git push
          fi

