name: Update YouTube videos

on:
  workflow_dispatch: # permet le lancement manuel
  schedule:
    - cron: "0 * * * *" # toutes les heures

jobs:
  fetch-youtube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Fetch latest YouTube videos
        run: node .github/workflows/scripts/fetch_youtube_rss.mjs

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/youtube.json
          git commit -m "Update YouTube videos" || echo "No changes to commit"
          git push


